(define (domain kartikeya-faran)
  (:requirements :typing :adl)
  (:types car grid)
  (:predicates (carfrom ?c - car ?x - grid ?y - grid)
  		   (samelength ?x - grid ?y - grid ?z - grid ?w - grid)
			(isinbetween ?init - grid ?mid - grid ?final - grid)
  		   )

  (:action move
    :parameters (?carnum - car ?initx ?inity ?finx ?finy - grid)
    :precondition (and (carfrom ?carnum ?initx ?inity)
		       (samelength ?initx ?inity ?finx ?finy)
		       (forall (?midpos - grid) 
						(imply (isinbetween ?finx ?midpos ?initx) 
							(or (isinbetween ?initx ?midpos ?inity)
								(forall (?t1 - grid) 
									(forall (?t2 - grid)
										(forall (?c1 - car)
											(imply (carfrom ?c1 ?t1 ?t2)
												(or (= ?c1 ?carnum)
													(not (isinbetween ?t1 ?midpos ?t2))
												)
											)
										)
									)
								)
							)
						)
					)
		       )
    :effect (and (not(carfrom ?carnum ?initx ?inity)) (carfrom ?carnum ?finx ?finy)))
  )
