(define (domain Far)
(:requirements :typing :adl)
(:types car grid )
(:predicates (free ?x - grid)
 (position ?x - car ?y - grid ?z - grid)
 (horizontal ?x - car)
 (vertical ?x - car)
 (neighbourup ?x - grid ?y - grid)
 (neighbourleft ?x - grid ?y - grid))
(:action move_up2_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?internal1 ?internal0)
 (free ?external0))
:effect (and 
 (free ?internal1 )
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external0 ?internal0))
)
(:action move_up2_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?internal1 ?internal0)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external1 ?external0))
)
(:action move_up2_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external2 ?external1))
)
(:action move_up2_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external3 ?external2))
)
(:action move_up2_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external4))
 (not(free ?external3))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external4 ?external3))
)
(:action move_up2_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?external4 ?external5)
 (neighbourup ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external5))
 (not(free ?external4))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external5 ?external4))
)
(:action move_up2_7
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?external4 ?external5)
 (neighbourup ?external5 ?external6)
 (neighbourup ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external6))
 (not(free ?external5))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external6 ?external5))
)
(:action move_up2_8
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid ?external7 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?external4 ?external5)
 (neighbourup ?external5 ?external6)
 (neighbourup ?external6 ?external7)
 (neighbourup ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6)
 (free ?external7))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external7))
 (not(free ?external6))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external7 ?external6))
)
(:action move_up3_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (free ?external0))
:effect (and 
 (free ?internal2 )
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external0 ?internal1))
)
(:action move_up3_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external1 ?internal0))
)
(:action move_up3_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external2 ?external0))
)
(:action move_up3_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external3 ?external1))
)
(:action move_up3_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external4 ?external2))
)
(:action move_up3_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?external4 ?external5)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external5))
 (not(free ?external4))
 (not(free ?external3))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external5 ?external3))
)
(:action move_up3_7
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?external4 ?external5)
 (neighbourup ?external5 ?external6)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external6))
 (not(free ?external5))
 (not(free ?external4))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external6 ?external4))
)
(:action move_up4_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (neighbourup ?internal3 ?internal2)
 (free ?external0))
:effect (and 
 (free ?internal3 )
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external0 ?internal2))
)
(:action move_up4_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (neighbourup ?internal3 ?internal2)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external1 ?internal1))
)
(:action move_up4_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (neighbourup ?internal3 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external2 ?internal0))
)
(:action move_up4_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (neighbourup ?internal3 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external3 ?external0))
)
(:action move_up4_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (neighbourup ?internal3 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external4 ?external1))
)
(:action move_up4_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourup ?internal0 ?external0)
 (neighbourup ?external0 ?external1)
 (neighbourup ?external1 ?external2)
 (neighbourup ?external2 ?external3)
 (neighbourup ?external3 ?external4)
 (neighbourup ?external4 ?external5)
 (neighbourup ?internal1 ?internal0)
 (neighbourup ?internal2 ?internal1)
 (neighbourup ?internal3 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external5))
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external5 ?external2))
)
(:action move_down2_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?internal0 ?internal1)
 (free ?external0))
:effect (and 
 (free ?internal1 )
 (not(free ?external0))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?internal0 ?external0))
)
(:action move_down2_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?internal0 ?internal1)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external0 ?external1))
)
(:action move_down2_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external1 ?external2))
)
(:action move_down2_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external2 ?external3))
)
(:action move_down2_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external4))
 (not(free ?external3))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external3 ?external4))
)
(:action move_down2_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?external5 ?external4)
 (neighbourup ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external5))
 (not(free ?external4))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external4 ?external5))
)
(:action move_down2_7
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?external5 ?external4)
 (neighbourup ?external6 ?external5)
 (neighbourup ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external6))
 (not(free ?external5))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external5 ?external6))
)
(:action move_down2_8
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid ?external7 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?external5 ?external4)
 (neighbourup ?external6 ?external5)
 (neighbourup ?external7 ?external6)
 (neighbourup ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6)
 (free ?external7))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external7))
 (not(free ?external6))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external6 ?external7))
)
(:action move_down3_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (free ?external0))
:effect (and 
 (free ?internal2 )
 (not(free ?external0))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?internal1 ?external0))
)
(:action move_down3_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?internal0 ?external1))
)
(:action move_down3_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external0 ?external2))
)
(:action move_down3_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external1 ?external3))
)
(:action move_down3_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external2 ?external4))
)
(:action move_down3_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?external5 ?external4)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external5))
 (not(free ?external4))
 (not(free ?external3))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external3 ?external5))
)
(:action move_down3_7
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?external5 ?external4)
 (neighbourup ?external6 ?external5)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external6))
 (not(free ?external5))
 (not(free ?external4))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external4 ?external6))
)
(:action move_down4_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (neighbourup ?internal2 ?internal3)
 (free ?external0))
:effect (and 
 (free ?internal3 )
 (not(free ?external0))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?internal2 ?external0))
)
(:action move_down4_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (neighbourup ?internal2 ?internal3)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?internal1 ?external1))
)
(:action move_down4_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (neighbourup ?internal2 ?internal3)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?internal0 ?external2))
)
(:action move_down4_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (neighbourup ?internal2 ?internal3)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?external0 ?external3))
)
(:action move_down4_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (neighbourup ?internal2 ?internal3)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?external1 ?external4))
)
(:action move_down4_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (vertical ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourup ?external0 ?internal0)
 (neighbourup ?external1 ?external0)
 (neighbourup ?external2 ?external1)
 (neighbourup ?external3 ?external2)
 (neighbourup ?external4 ?external3)
 (neighbourup ?external5 ?external4)
 (neighbourup ?internal0 ?internal1)
 (neighbourup ?internal1 ?internal2)
 (neighbourup ?internal2 ?internal3)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external5))
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?external2 ?external5))
)
(:action move_left2_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?internal1 ?internal0)
 (free ?external0))
:effect (and 
 (free ?internal1 )
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external0 ?internal0))
)
(:action move_left2_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?internal1 ?internal0)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external1 ?external0))
)
(:action move_left2_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external2 ?external1))
)
(:action move_left2_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external3 ?external2))
)
(:action move_left2_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external4))
 (not(free ?external3))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external4 ?external3))
)
(:action move_left2_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?external4 ?external5)
 (neighbourleft ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external5))
 (not(free ?external4))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external5 ?external4))
)
(:action move_left2_7
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?external4 ?external5)
 (neighbourleft ?external5 ?external6)
 (neighbourleft ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external6))
 (not(free ?external5))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external6 ?external5))
)
(:action move_left2_8
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid ?external7 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal1)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?external4 ?external5)
 (neighbourleft ?external5 ?external6)
 (neighbourleft ?external6 ?external7)
 (neighbourleft ?internal1 ?internal0)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6)
 (free ?external7))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external7))
 (not(free ?external6))
 (not(position ?x ?internal0 ?internal1))
 (position ?x ?external7 ?external6))
)
(:action move_left3_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (free ?external0))
:effect (and 
 (free ?internal2 )
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external0 ?internal1))
)
(:action move_left3_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external1 ?internal0))
)
(:action move_left3_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external2 ?external0))
)
(:action move_left3_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external3 ?external1))
)
(:action move_left3_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external4 ?external2))
)
(:action move_left3_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?external4 ?external5)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external5))
 (not(free ?external4))
 (not(free ?external3))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external5 ?external3))
)
(:action move_left3_7
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal2)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?external4 ?external5)
 (neighbourleft ?external5 ?external6)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external6))
 (not(free ?external5))
 (not(free ?external4))
 (not(position ?x ?internal0 ?internal2))
 (position ?x ?external6 ?external4))
)
(:action move_left4_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (neighbourleft ?internal3 ?internal2)
 (free ?external0))
:effect (and 
 (free ?internal3 )
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external0 ?internal2))
)
(:action move_left4_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (neighbourleft ?internal3 ?internal2)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external1 ?internal1))
)
(:action move_left4_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (neighbourleft ?internal3 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external2 ?internal0))
)
(:action move_left4_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (neighbourleft ?internal3 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external3 ?external0))
)
(:action move_left4_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (neighbourleft ?internal3 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external4 ?external1))
)
(:action move_left4_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal0 ?internal3)
 (neighbourleft ?internal0 ?external0)
 (neighbourleft ?external0 ?external1)
 (neighbourleft ?external1 ?external2)
 (neighbourleft ?external2 ?external3)
 (neighbourleft ?external3 ?external4)
 (neighbourleft ?external4 ?external5)
 (neighbourleft ?internal1 ?internal0)
 (neighbourleft ?internal2 ?internal1)
 (neighbourleft ?internal3 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external5))
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal0 ?internal3))
 (position ?x ?external5 ?external2))
)
(:action move_right2_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?internal0 ?internal1)
 (free ?external0))
:effect (and 
 (free ?internal1 )
 (not(free ?external0))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?internal0 ?external0))
)
(:action move_right2_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?internal0 ?internal1)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external0 ?external1))
)
(:action move_right2_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external1 ?external2))
)
(:action move_right2_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external2 ?external3))
)
(:action move_right2_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external4))
 (not(free ?external3))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external3 ?external4))
)
(:action move_right2_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?external5 ?external4)
 (neighbourleft ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external5))
 (not(free ?external4))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external4 ?external5))
)
(:action move_right2_7
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?external5 ?external4)
 (neighbourleft ?external6 ?external5)
 (neighbourleft ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external6))
 (not(free ?external5))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external5 ?external6))
)
(:action move_right2_8
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid ?external7 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal1 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?external5 ?external4)
 (neighbourleft ?external6 ?external5)
 (neighbourleft ?external7 ?external6)
 (neighbourleft ?internal0 ?internal1)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6)
 (free ?external7))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (not(free ?external7))
 (not(free ?external6))
 (not(position ?x ?internal1 ?internal0 ))
 (position ?x  ?external6 ?external7))
)
(:action move_right3_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (free ?external0))
:effect (and 
 (free ?internal2 )
 (not(free ?external0))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?internal1 ?external0))
)
(:action move_right3_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?internal0 ?external1))
)
(:action move_right3_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external0 ?external2))
)
(:action move_right3_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external1 ?external3))
)
(:action move_right3_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external2 ?external4))
)
(:action move_right3_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?external5 ?external4)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external5))
 (not(free ?external4))
 (not(free ?external3))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external3 ?external5))
)
(:action move_right3_7
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid ?external6 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal2 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?external5 ?external4)
 (neighbourleft ?external6 ?external5)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5)
 (free ?external6))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (not(free ?external6))
 (not(free ?external5))
 (not(free ?external4))
 (not(position ?x ?internal2 ?internal0 ))
 (position ?x  ?external4 ?external6))
)
(:action move_right4_1
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (neighbourleft ?internal2 ?internal3)
 (free ?external0))
:effect (and 
 (free ?internal3 )
 (not(free ?external0))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?internal2 ?external0))
)
(:action move_right4_2
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (neighbourleft ?internal2 ?internal3)
 (free ?external0)
 (free ?external1))
:effect (and 
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?internal1 ?external1))
)
(:action move_right4_3
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (neighbourleft ?internal2 ?internal3)
 (free ?external0)
 (free ?external1)
 (free ?external2))
:effect (and 
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?internal0 ?external2))
)
(:action move_right4_4
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (neighbourleft ?internal2 ?internal3)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(free ?external0))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?external0 ?external3))
)
(:action move_right4_5
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (neighbourleft ?internal2 ?internal3)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(free ?external1))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?external1 ?external4))
)
(:action move_right4_6
:parameters (?x - car ?internal0 - grid ?internal1 - grid ?internal2 - grid ?internal3 - grid ?external0 - grid ?external1 - grid ?external2 - grid ?external3 - grid ?external4 - grid ?external5 - grid )
:precondition (and 
 (horizontal ?x) 
 (position ?x ?internal3 ?internal0 )
 (neighbourleft ?external0 ?internal0)
 (neighbourleft ?external1 ?external0)
 (neighbourleft ?external2 ?external1)
 (neighbourleft ?external3 ?external2)
 (neighbourleft ?external4 ?external3)
 (neighbourleft ?external5 ?external4)
 (neighbourleft ?internal0 ?internal1)
 (neighbourleft ?internal1 ?internal2)
 (neighbourleft ?internal2 ?internal3)
 (free ?external0)
 (free ?external1)
 (free ?external2)
 (free ?external3)
 (free ?external4)
 (free ?external5))
:effect (and 
 (free ?internal0 )
 (free ?internal1 )
 (free ?internal2 )
 (free ?internal3 )
 (not(free ?external5))
 (not(free ?external4))
 (not(free ?external3))
 (not(free ?external2))
 (not(position ?x ?internal3 ?internal0 ))
 (position ?x  ?external2 ?external5))
)
)